# Generated by Django 5.1.2 on 2024-10-09 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='response',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='school',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.response')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='answers',
            field=models.ManyToManyField(through='feedback.Answer', to='feedback.question'),
        ),
    ]
