# Generated by Django 5.1.2 on 2024-10-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_text_question_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='school',
        ),
    ]
